name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Run Premake
      - name: Run Premake
        uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      # Run Premake
      - name: Run premake
        run: premake5 vs2022

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Run MSBuild
        run: msbuild TrianGL.sln -t:rebuild -verbosity:n -property:Configuration=Debug
