name: build-project
on: [push]
jobs:
  setup-premake:
    runs-on: windows-latest
    steps:
      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"
      - run: premake5 vs2022 --file=../premake5.lua
